// lib/crystalData.ts
// AUTO-GENERATED from the tagging script's dictionaries so the frontend's
// crystal/purpose lists exactly match the tags written to your products.
// Safe to hand-edit: add cover images in CRYSTAL_IMAGES / PURPOSE_IMAGES below.
import { toSlug } from '@/lib/shopTaxonomy'

export const CRYSTALS: string[] = [
  "Agate",
  "Alexandrite",
  "Almandine",
  "Amazonite",
  "Amber",
  "Amethyst",
  "Ametrine",
  "Ammolite",
  "Ammonite",
  "Angelite",
  "Apache Tear",
  "Apatite",
  "Apophyllite",
  "Aquamarine",
  "Aragonite",
  "Astrophyllite",
  "Aventurine",
  "Azurite",
  "Banded Agate",
  "Barite",
  "Beryl",
  "Black Kyanite",
  "Black Moonstone",
  "Black Obsidian",
  "Black Onyx",
  "Black Tourmaline",
  "Bloodstone",
  "Blue Aragonite",
  "Blue Aventurine",
  "Blue Calcite",
  "Blue Goldstone",
  "Blue Kyanite",
  "Blue Lace Agate",
  "Blue Quartz",
  "Blue Sandstone",
  "Blue Sapphire",
  "Blue Tiger Eye",
  "Blue Topaz",
  "Blue Tourmaline",
  "Botswana Agate",
  "Brazilianite",
  "Brecciated Jasper",
  "Bronzite",
  "Calcite",
  "Carnelian",
  "Cats Eye",
  "Cavansite",
  "Celestite",
  "Cerussite",
  "Chalcedony",
  "Charoite",
  "Cherry Quartz",
  "Chevron Amethyst",
  "Chiastolite",
  "Chrome Diopside",
  "Chrysoberyl",
  "Chrysocolla",
  "Chrysoprase",
  "Cinnabar",
  "Citrine",
  "Clear Quartz",
  "Common Opal",
  "Copal",
  "Coral",
  "Crazy Lace Agate",
  "Crocoite",
  "Cuprite",
  "Dalmatian Jasper",
  "Danburite",
  "Datolite",
  "Dendritic Agate",
  "Desert Rose",
  "Diamond",
  "Diopside",
  "Dioptase",
  "Dolomite",
  "Dumortierite",
  "Emerald",
  "Epidote",
  "Ethiopian Opal",
  "Eudialyte",
  "Fire Agate",
  "Fire Opal",
  "Fluorite",
  "Fuchsite",
  "Galena",
  "Garnet",
  "Gold Sandstone",
  "Gold Sheen Obsidian",
  "Goldstone",
  "Goshenite",
  "Green Aventurine",
  "Green Calcite",
  "Green Fluorite",
  "Green Jade",
  "Green Kyanite",
  "Green Tourmaline",
  "Gypsum",
  "Hawk Eye",
  "Heliodor",
  "Hematite",
  "Hemimorphite",
  "Herkimer Diamond",
  "Hessonite",
  "Heulandite",
  "Hiddenite",
  "Honey Calcite",
  "Howlite",
  "Hypersthene",
  "Imperial Topaz",
  "Iolite",
  "Jade",
  "Jadeite",
  "Jasper",
  "Jet",
  "Kambaba Jasper",
  "Kunzite",
  "Kyanite",
  "Labradorite",
  "Lapis Lazuli",
  "Larimar",
  "Larvikite",
  "Lava Stone",
  "Lavender Jade",
  "Lazulite",
  "Lemon Quartz",
  "Leopard Skin Jasper",
  "Lepidolite",
  "Libyan Desert Glass",
  "Lithium Quartz",
  "Llanite",
  "Lodestone",
  "Lodolite",
  "Magnesite",
  "Magnetite",
  "Mahogany Obsidian",
  "Malachite",
  "Mangano Calcite",
  "Marcasite",
  "Milky Quartz",
  "Moldavite",
  "Mookaite",
  "Moonstone",
  "Morganite",
  "Moss Agate",
  "Mother of Pearl",
  "Navratna",
  "Nephrite",
  "Nuummite",
  "Obsidian",
  "Ocean Jasper",
  "Onyx",
  "Opal",
  "Opalite",
  "Orange Calcite",
  "Peach Moonstone",
  "Peacock Ore",
  "Pearl",
  "Peridot",
  "Petalite",
  "Phantom Quartz",
  "Phenacite",
  "Phosphosiderite",
  "Picture Jasper",
  "Pietersite",
  "Pink Opal",
  "Pink Sapphire",
  "Pink Tourmaline",
  "Prasiolite",
  "Prehnite",
  "Pumice",
  "Purple Fluorite",
  "Purpurite",
  "Pyrite",
  "Pyrope",
  "Quartz",
  "Rainbow Fluorite",
  "Rainbow Moonstone",
  "Rainbow Obsidian",
  "Realgar",
  "Red Aventurine",
  "Red Calcite",
  "Red Coral",
  "Red Jasper",
  "Red Tiger Eye",
  "Rhodochrosite",
  "Rhodolite",
  "Rhodonite",
  "Rhyolite",
  "Rose Quartz",
  "Ruby",
  "Ruby Kyanite",
  "Ruby Zoisite",
  "Rudraksha",
  "Rutilated Quartz",
  "Sandalwood",
  "Sandstone",
  "Sapphire",
  "Sard",
  "Sardonyx",
  "Satin Spar",
  "Scolecite",
  "Selenite",
  "Septarian",
  "Seraphinite",
  "Serpentine",
  "Seven Chakra",
  "Shattuckite",
  "Shell",
  "Shiva Lingam",
  "Shungite",
  "Smithsonite",
  "Smoky Quartz",
  "Snow Quartz",
  "Snowflake Obsidian",
  "Sodalite",
  "Spectrolite",
  "Spessartine",
  "Sphatik",
  "Sphene",
  "Spinel",
  "Spirit Quartz",
  "Star Sapphire",
  "Stilbite",
  "Strawberry Quartz",
  "Sugilite",
  "Sulemani Hakik",
  "Sunstone",
  "Super Seven",
  "Tanzanite",
  "Tektite",
  "Terahertz",
  "Thulite",
  "Tiger Eye",
  "Tiger Iron",
  "Topaz",
  "Tourmalinated Quartz",
  "Tourmaline",
  "Tree Agate",
  "Triple Protection",
  "Tsavorite",
  "Tulsi",
  "Turquoise",
  "Unakite",
  "Vanadinite",
  "Variscite",
  "Vesuvianite",
  "Watermelon Tourmaline",
  "White Jade",
  "White Sapphire",
  "Wulfenite",
  "Yellow Jade",
  "Yellow Jasper",
  "Yellow Sapphire",
  "Zeolite",
  "Zircon",
  "Zoisite",
]

export const CRYSTAL_SET = new Set(CRYSTALS.map((c) => c.toLowerCase()))
export const isCrystalTag = (tag: string) => CRYSTAL_SET.has(tag.trim().toLowerCase())

export interface PurposeMeta { key: string; icon: string }
export const PURPOSES: PurposeMeta[] = [
  { key: "Abundance & Wealth", icon: "\ud83d\udcb0" },
  { key: "Love & Relationships", icon: "\u2764\ufe0f" },
  { key: "Protection & Cleansing", icon: "\ud83d\udee1\ufe0f" },
  { key: "Healing & Wellness", icon: "\ud83c\udf3f" },
  { key: "Meditation & Spirituality", icon: "\ud83e\uddd8" },
  { key: "Calm & Stress Relief", icon: "\ud83c\udf19" },
  { key: "Confidence & Power", icon: "\ud83d\udd25" },
  { key: "Intuition & Clarity", icon: "\ud83d\udc41\ufe0f" },
  { key: "Communication & Expression", icon: "\ud83d\udde3\ufe0f" },
  { key: "Grounding & Stability", icon: "\ud83c\udf0d" },
]
export const PURPOSE_SET = new Set(PURPOSES.map((p) => p.key.toLowerCase()))
export const isPurposeTag = (tag: string) => PURPOSE_SET.has(tag.trim().toLowerCase())
export const purposeIcon = (key: string) =>
  PURPOSES.find((p) => p.key.toLowerCase() === key.toLowerCase())?.icon || '✦'

// ── Cover images ──────────────────────────────────────────────────────────
// Fill these in to show a custom cover per crystal / purpose (like the
// reference site). Any not listed here fall back to a representative product
// photo automatically. Keys are matched case-insensitively.
// Example:  'Amethyst': 'https://your-cdn/amethyst.jpg',
export const CRYSTAL_IMAGES: Record<string, string> = {
  // 'Amethyst': '',
}
export const PURPOSE_IMAGES: Record<string, string> = {
  // 'Abundance & Wealth': '',
}
export const coverFor = (
  map: Record<string, string>, name: string,
): string | undefined => {
  const hit = Object.keys(map).find((k) => k.toLowerCase() === name.toLowerCase())
  return hit ? map[hit] : undefined
}

// ── S3 / CDN cover images ─────────────────────────────────────────
// Set CRYSTAL_IMAGE_BASE once to the S3/CloudFront folder your crystal PNGs
// live in (NO trailing slash), e.g.
//   export const CRYSTAL_IMAGE_BASE =
//     'https://your-bucket.s3.ap-south-1.amazonaws.com/crystals'
// The objects must be publicly readable over HTTPS (bucket policy or
// CloudFront) — not pre-signed URLs. Leave '' to keep product-photo fallbacks.
// Each cover resolves to  <base>/<exact filename>  from CRYSTAL_COVER_FILES.
// Any crystal without a file quietly falls back to a product photo.
export const CRYSTAL_IMAGE_BASE = 'https://thecosmicconnect-crystal-cover-images.s3.ap-south-1.amazonaws.com'

// Generated from your uploaded "_1" cover files: canonical crystal -> exact
// filename. Only crystals listed here get a real cover; every other crystal
// automatically uses a representative product photo.
export const CRYSTAL_COVER_FILES: Record<string, string> = {
  "Amazonite": "Amazonite_1.png",
  "Amber": "Amber_1.png",
  "Amethyst": "Amethyst_1.png",
  "Ametrine": "Ametrine_1.png",
  "Angelite": "Angelite_1.png",
  "Apatite": "Blue Apatite_1.png",
  "Apophyllite": "Apophyllite_1.png",
  "Aquamarine": "Aquamarine_1.png",
  "Aragonite": "Aragonite_1.png",
  "Astrophyllite": "Astrophyllite_1.png",
  "Black Obsidian": "Black Obsidian_1.png",
  "Black Tourmaline": "Black Tourmaline_1.png",
  "Bloodstone": "Bloodstone_1.png",
  "Blue Aventurine": "Blue Aventurine_1.png",
  "Blue Lace Agate": "Blue Lace Agate_1.png",
  "Blue Quartz": "Blue Quartz_1.png",
  "Blue Sandstone": "Blue Sandstone_1.png",
  "Blue Sapphire": "Blue Sapphire_1.png",
  "Blue Topaz": "Blue Topaz_1.png",
  "Calcite": "Calcite_1.png",
  "Carnelian": "Carnelian_1.png",
  "Citrine": "Citrine_1.png",
  "Clear Quartz": "Clear Quartz_1.png",
  "Dalmatian Jasper": "Dalmatian Jasper_1.png",
  "Emerald": "Emerald_1.png",
  "Fire Agate": "Fire Agate_1.png",
  "Fluorite": "Fluorite_1.png",
  "Green Aventurine": "Green Aventurine_1.png",
  "Green Fluorite": "Green Fluorite_1.png",
  "Green Jade": "Green Jade_1.png",
  "Hematite": "Hematite_1.png",
  "Howlite": "Howlite_1.png",
  "Iolite": "Iolite_1.png",
  "Labradorite": "Labradorite_1.png",
  "Lapis Lazuli": "Lapis Lazuli_1.png",
  "Larimar": "Larimar_1.png",
  "Larvikite": "Larvikite_1.png",
  "Lava Stone": "Lava Stone_1.png",
  "Lemon Quartz": "Lemon Quartz_1.png",
  "Lepidolite": "Lepidolite_1.png",
  "Llanite": "Llanite_1.png",
  "Mahogany Obsidian": "Mahogany Obsidian_1.png",
  "Malachite": "Malachite_1.png",
  "Moonstone": "Moonstone_1.png",
  "Moss Agate": "Moss Agate_1.png",
  "Opal": "Opal_1.png",
  "Opalite": "Opalite_1.png",
  "Pearl": "Pearl_1.png",
  "Peridot": "Peridot_1.png",
  "Picture Jasper": "Picture Jasper_1.png",
  "Pink Tourmaline": "Pink Tourmaline_1.png",
  "Prehnite": "Prehnite_1.png",
  "Pyrite": "Pyrite_1.png",
  "Rainbow Moonstone": "Rainbow Moonstone_1.png",
  "Red Aventurine": "Red Aventurine_1.png",
  "Red Jasper": "Red Jasper_1.png",
  "Rhodochrosite": "Rhodochrosite_1.png",
  "Rhodonite": "Rhodonite_1.png",
  "Rose Quartz": "Rose Quartz_1.png",
  "Ruby": "Ruby_1.png",
  "Selenite": "Selenite_1.png",
  "Serpentine": "Serpentine_1.png",
  "Shungite": "Shungite_1.png",
  "Smoky Quartz": "Smoky Quartz_1.png",
  "Snowflake Obsidian": "Snowflake Obsidian_1.png",
  "Sodalite": "Sodalite_1.png",
  "Strawberry Quartz": "Strawberry Quartz_1.png",
  "Sulemani Hakik": "Sulemani Hakik_1.png",
  "Sunstone": "Sunstone_1.png",
  "Tiger Eye": "Tiger Eye_1.png",
  "Tourmaline": "Tourmaline_1.png",
  "Turquoise": "Turquoise_1.png",
  "Unakite": "Unakite_1.png",
  "Yellow Jade": "Yellow Jade_1.png",
}

export function crystalCoverUrl(name: string): string {
  const override = coverFor(CRYSTAL_IMAGES, name)
  if (override) return override
  const file =
    CRYSTAL_COVER_FILES[name] ||
    Object.entries(CRYSTAL_COVER_FILES).find(([k]) => k.toLowerCase() === name.toLowerCase())?.[1]
  if (!file || !CRYSTAL_IMAGE_BASE) return ''
  // Covers are uploaded as optimized .webp (see optimize_covers.py)
  const webp = file.replace(/\.png$/i, '.webp')
  return `${CRYSTAL_IMAGE_BASE}/${encodeURIComponent(webp)}`
}

// Same idea for purpose covers (optional — leave base '' to use product photos).
export const PURPOSE_IMAGE_BASE = ''
export const PURPOSE_IMAGE_EXT = 'png'
export function purposeCoverUrl(key: string): string {
  const override = coverFor(PURPOSE_IMAGES, key)
  if (override) return override
  return PURPOSE_IMAGE_BASE ? `${PURPOSE_IMAGE_BASE}/${toSlug(key)}.${PURPOSE_IMAGE_EXT}` : ''
}
